name: 想法的猫
description: >
     ThinkingMore.
about: >
     Android。


url: ""
baseurl: "" 
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate,  jekyll-gist]

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           想法的猫
  avatar:         "https://avatars3.githubusercontent.com/u/36157582?s=400&u=cf5598b9a0abbac78ade8b5053237b5267c98bb8&v=4"
  email:          "xiangfademao@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:          "https://github.com/xiangfademao"
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
